language: csharp
dist: trusty
mono: none
dotnet: 2.0.0
before_install:
- sudo add-apt-repository ppa:octave/stable -y
- sudo apt-get update -y
- sudo apt-get install octave -y

install:
- cd src
- dotnet restore

script:
- dotnet test Octave.NET.Tests -v q